# Generated by Django 4.1.7 on 2023-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criacao"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Quantidade"
                    ),
                ),
                (
                    "codigo",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Codigo"
                    ),
                ),
                (
                    "preferencia",
                    models.CharField(max_length=10, verbose_name="Preferencia"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateField(auto_now_add=True, verbose_name="Data de Criacao"),
                ),
                (
                    "modificado",
                    models.DateField(auto_now=True, verbose_name="Data de Atualização"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "codigo",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Codigo"
                    ),
                ),
                (
                    "destino",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Destino"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
