# Generated by Django 4.1.7 on 2023-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="codigo",
            field=models.DecimalField(
                decimal_places=0, max_digits=4, verbose_name="Codigo"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=0, max_digits=3, verbose_name="Quantidade"
            ),
        ),
        migrations.AlterField(
            model_name="transferencia",
            name="codigo",
            field=models.DecimalField(
                decimal_places=0, max_digits=4, verbose_name="Codigo"
            ),
        ),
        migrations.AlterField(
            model_name="transferencia",
            name="destino",
            field=models.DecimalField(
                decimal_places=0, max_digits=4, verbose_name="Destino"
            ),
        ),
    ]
