# Generated by Django 4.1.7 on 2023-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_cliente_codigo_alter_cliente_quantidade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferencia",
            name="codigo",
            field=models.CharField(max_length=4, verbose_name="Codigo"),
        ),
        migrations.AlterField(
            model_name="transferencia",
            name="destino",
            field=models.CharField(max_length=4, verbose_name="Destino"),
        ),
    ]
